USE [Amlak-Parsa]
GO
IF EXISTS(SELECT 1 FROM SYS.PROCEDURES WHERE [object_id] = OBJECT_ID('ptl.spDeleteEvents'))
	DROP PROCEDURE ptl.spDeleteEvents
GO

CREATE PROCEDURE ptl.spDeleteEvents
@ID UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;
	DELETE FROM [ptl].[Events] WHERE ID = @ID
	RETURN @@ROWCOUNT
END